### ISSUE TITLE
Ignore trailing slash

### ISSUE THREAD

**Issue by Jamie452** [jkyberneees/fast-gateway#12]
Is it possible to ignore trailing slashes when requesting a prefix directly?

I tried to pass `ignoreTrailingSlash: true` as a `restana` config option but had no luck.

Wondering if there's a reason this behaviour is not available?

**Comment by jkyberneees** [comment]
Hi @Jamie452 thanks for reaching out. 
Could you please checkout the `pathRegex` config of the `fast-gateway` module. I guess modifying the default value would work for you. 

In other case, can you please describe with an example what you are trying to get?

Looking forward to hear more from you.
