### ISSUE TITLE
Handle routes timeout and unavailability  

### ISSUE THREAD

**Issue by nandanugg** [jkyberneees/fast-gateway#14]
Hi, Just curious how can I handle that? Seems I can't find a single clue.

**Comment by jkyberneees** [comment]
Hi @nandanugg, you are right. This features are not implemented actually. 
I will get back to you with a followup ASAP.

**Comment by jkyberneees** [comment]
JFYI: https://github.com/jkyberneees/fast-proxy/pull/4
Circuit breaker solution coming afterwards...

**Comment by jkyberneees** [comment]
Hi @nandanugg, please check out: https://github.com/jkyberneees/fast-gateway/releases/tag/v1.4.0

Regards
