### ISSUE TITLE
Internal route for health check

### ISSUE THREAD

**Issue by maxmartinezc** [jkyberneees/fast-gateway#29]
Hello, 
is it possible to implement an internal router for health check (/ health, / readiness, / liveness) ?

Thank's

**Comment by maxmartinezc** [comment]
My workaround is:

`
const server = gateway({
  middlewares: [
    Cors(),
    bodyParser.json()
  ], 
  routes: [{
    prefix: '/health',
    methods: ['GET'],
    hooks: {
      async onRequest(req, res) {
        res.send({ status: 'UP' });
        return true;
      }
    }
  }]
});
`

**Comment by jkyberneees** [comment]
Hi @maxmartinezc, excuses for reaching out a bit late. You can simply setup your health check using restana routes. Please see example below:

```js
const service = gateway({
  routes: [{
    prefix: '/service',
    target: 'http://127.0.0.1:3000'
  }]
})

service.get('/health', (req, res) => {
  res.send({
    status: 'OK'
  })
})

service.start(PORT).then(server => {
  console.log(`API Gateway listening on ${PORT} port!`)
})
```
Your solution also works, but I would take this one instead for performance reasons. 

Thanks again for reaching out.

**Comment by angherq** [comment]
I am doing something similar but I have a middleware enabled in the gateway obj, it looks like the middleware is executing always. Is there a way to prevent the middleware to run when we go to http://127.0.0.1:3000/whateverNotMatchingThePrefix. Hope to be clear!

**Comment by jkyberneees** [comment]
Hi @angherq, thanks for reaching out. 
Can you please attach some code snippet that can describe your configuration?

Thanks
