### ISSUE TITLE
cache doesn't work when I use prefixRewrite option

### ISSUE THREAD

**Issue by fjc2112** [jkyberneees/fast-gateway#43]
I'm configuring an API gateway using "fast-gateway" and "http-cache-middleware", my problem is that if I use prefixRewrite option on routes the cache doesn't work. Here is a minimal example:
```
// api-gateway https://exposed-api.com

import gateway from 'fast-gateway';
const cache = require('http-cache-middleware')();

const server = gateway({
  middlewares: [
    cache,
  ],
  routes: [
    {
      prefix: '/service1',
      target: 'https://service-api.com',
    },
    {
      prefix: '/gateway/service2',
      prefixRewrite: '/service2',
      target: 'https://service-api.com',
    },
  ],
});
```

My service routes are:

service-api.com/service1
service-api.com/service2
In the first route, I have to send the request to https://exposed-api.com/service1/service1 and cache works.

In the second route, I have to send the request to https://exposed-api.com/gateway/service2 and here the cache doesn't work.

The thing is I need a common prefix (/gateway) on all routes, is there any way to make cache work using prefixRewrite?. Thanks!

**Comment by jkyberneees** [comment]
Hi @fjc2112, thanks for reaching out for support on this. As you can see here: https://github.com/jkyberneees/http-cache-middleware/blob/master/index.js#L34, the `http-cache-middleware` module is not affected by any url change (in your setup).

I am not sure if I understood correctly your setup. Can you describe the scenario without cache, so I can send you a configuration example back?

Regards

**Comment by fjc2112** [comment]
Hi thanks for your comments, The cache works fine, my problem was that the server responds 304 so the middleware ignores it. I close the issue
