### ISSUE TITLE
How does fast-gatewate operate features like Authentication & Authorisation?

### ISSUE THREAD

**Issue by phuocnguyen286** [jkyberneees/fast-gateway#55]
Hi,

I've read your medium article and your sample code. I just only see that fast-gateway handle as a proxy, recevei a request and pass it to another server. How about other feature such as authenticatin and authorization, logging, cache..?

**Comment by jkyberneees** [comment]
Hi @phuocnguyen286, thanks for reaching out fo help.

It is actually very simple, fast-gateway is built of on of https://www.npmjs.com/package/restana, so you can use connect-like middlewares. Optionally you can also use Expressjs as a base framework.

Developers can just connect global and route level middlewares (as described in the documentation). Please see a combined example here:
- https://github.com/jkyberneees/fast-gateway/blob/master/demos/basic.js 

Do not hesitate to contact us again if needed. 
Regards
